version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: docker
    ports:
      - 8686:8080
    volumes:
      - ./app:/app
    tty: true
    env_file:
      - .env
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_TIMEZONE: Asia/Tokyo
      PROJECT_ENV: docker

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
      LANG: ja_JP.utf8
    volumes:
      - ./docker/postgres/seeds:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
