// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/recreation"
	"app/ent/schema"
	"app/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recreationFields := schema.Recreation{}.Fields()
	_ = recreationFields
	// recreationDescPublish is the schema descriptor for publish field.
	recreationDescPublish := recreationFields[8].Descriptor()
	// recreation.DefaultPublish holds the default value on creation for the publish field.
	recreation.DefaultPublish = recreationDescPublish.Default.(bool)
	// recreationDescCreatedAt is the schema descriptor for created_at field.
	recreationDescCreatedAt := recreationFields[9].Descriptor()
	// recreation.DefaultCreatedAt holds the default value on creation for the created_at field.
	recreation.DefaultCreatedAt = recreationDescCreatedAt.Default.(func() time.Time)
	// recreationDescUpdatedAt is the schema descriptor for updated_at field.
	recreationDescUpdatedAt := recreationFields[10].Descriptor()
	// recreation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	recreation.DefaultUpdatedAt = recreationDescUpdatedAt.Default.(func() time.Time)
	// recreation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	recreation.UpdateDefaultUpdatedAt = recreationDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
