// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/prefecture"
	"app/ent/profile"
	"app/ent/recreation"
	"app/ent/schema"
	"app/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	prefectureFields := schema.Prefecture{}.Fields()
	_ = prefectureFields
	// prefectureDescCreatedAt is the schema descriptor for created_at field.
	prefectureDescCreatedAt := prefectureFields[1].Descriptor()
	// prefecture.DefaultCreatedAt holds the default value on creation for the created_at field.
	prefecture.DefaultCreatedAt = prefectureDescCreatedAt.Default.(func() time.Time)
	// prefectureDescUpdatedAt is the schema descriptor for updated_at field.
	prefectureDescUpdatedAt := prefectureFields[2].Descriptor()
	// prefecture.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prefecture.DefaultUpdatedAt = prefectureDescUpdatedAt.Default.(func() time.Time)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescCreatedAt is the schema descriptor for created_at field.
	profileDescCreatedAt := profileFields[3].Descriptor()
	// profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	profile.DefaultCreatedAt = profileDescCreatedAt.Default.(func() time.Time)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileFields[4].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	recreationFields := schema.Recreation{}.Fields()
	_ = recreationFields
	// recreationDescCreatedAt is the schema descriptor for created_at field.
	recreationDescCreatedAt := recreationFields[7].Descriptor()
	// recreation.DefaultCreatedAt holds the default value on creation for the created_at field.
	recreation.DefaultCreatedAt = recreationDescCreatedAt.Default.(func() time.Time)
	// recreationDescUpdatedAt is the schema descriptor for updated_at field.
	recreationDescUpdatedAt := recreationFields[8].Descriptor()
	// recreation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	recreation.DefaultUpdatedAt = recreationDescUpdatedAt.Default.(func() time.Time)
	// recreation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	recreation.UpdateDefaultUpdatedAt = recreationDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
