// Code generated by ent, DO NOT EDIT.

package recreation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the recreation type in the database.
	Label = "recreation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldTargetNumber holds the string denoting the target_number field in the database.
	FieldTargetNumber = "target_number"
	// FieldRequredTime holds the string denoting the requred_time field in the database.
	FieldRequredTime = "requred_time"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the recreation in the database.
	Table = "recreations"
)

// Columns holds all SQL columns for recreation fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUUID,
	FieldGenre,
	FieldTitle,
	FieldTargetNumber,
	FieldRequredTime,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// Order defines the ordering method for the Recreation queries.
type Order func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUUID orders the results by the uuid field.
func ByUUID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByGenre orders the results by the genre field.
func ByGenre(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldGenre, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByTargetNumber orders the results by the target_number field.
func ByTargetNumber(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldTargetNumber, opts...).ToFunc()
}

// ByRequredTime orders the results by the requred_time field.
func ByRequredTime(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldRequredTime, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
