name: Deploy to Fly.io
on: push
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TOML_FILE: ./.github/workflows/fly.staging.toml
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      environment: STG
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: echo $FLY_API_TOKEN
        - run: echo $TOML_FILE
        - run: echo {{ env.TOML_FILE }}
        - run: ls -lah
        # - run: pwd
        # # dirがあるか確認する
        # - run: ls -lah ./.github
        - run: flyctl deploy --config $TOML_FILE --build-target deploy --remote-only
